### ISSUE TITLE
Support HTML imports

### ISSUE THREAD

**Issue by uncompiled** [cloudflare/netjet#25]
Is there any thought of supporting HTML imports via the link tag?

If an application uses web components, the author may choose to structure their pages by importing custom elements, such as:

`<link rel="import" href="custom-element.html">`

In this case, if the web components required for the initial render can be pushed, the assets will already be available in the browser cache.

I started working on adding support for HTML imports in my own [fork](https://github.com/uncompiled/netjet), but if this feature is something that you're interested in including, I'd love to help out.

**Comment by uncompiled** [comment]
Although it seems to be a valid option in the [preload spec](https://w3c.github.io/preload/#link-element-interface-extensions) and I am seeing `Push / (index)` from the Initiator column in Chrome Canary Dev Tools, I'm also seeing a warning:

`<link rel=preload> must have a valid `as` value`

There's an active [Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=593267) for this.

With that said, it looks like the [Polymer Shop demo](shop.polymer-project.org) is sending Link headers with the same format:

`Link: </bower_components/polymer/polymer.html>;rel=preload;as=document`

**Comment by uncompiled** [comment]
Sure, that makes sense to me.  Priority would benefit more people, since images are more common than HTML imports at this time.

The Preload spec is still in working draft, so I'll submit a PR to hold onto the idea.

**Comment by terinjokes** [comment]
@uncompiled Has there been an update on the preload spec?

**Comment by uncompiled** [comment]
It looks like the preload spec is still WIP, so I'm not sure it's desirable to include this feature until the preload spec is implemented by more browsers (and less potential for the spec to change under the implementation).

**Comment by terinjokes** [comment]
@uncompiled I agree. I'll keep this open for now.

**Comment by uncompiled** [comment]
Closing this issue because HTML imports have been dead for a while.
